name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm i
          npm run build

      - name: Semantic release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
          branches: | 
            ['master']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set env
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build release
        if: steps.semantic.outputs.new_release_published == 'true'
        shell: bash
        run: |
          npm run plugin-zip

      - name: Release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.semantic.outputs.new_release_version }}
          files: |
            course-catalog-block.zip